//===========================================================================
// 
// Just another Warcraft III map
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Map Author: Unknown
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
    // Generated
    trigger                 gg_trg_Melee_Initialization = null
endglobals

function InitGlobals takes nothing returns nothing
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateBuildingsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'unp2', 3072.0, 9344.0, 270.000, 'unp2' )
    set u = BlzCreateUnitWithSkin( p, 'uslh', 3392.0, 8768.0, 270.000, 'uslh' )
    set u = BlzCreateUnitWithSkin( p, 'utod', 2880.0, 8448.0, 270.000, 'utod' )
    set u = BlzCreateUnitWithSkin( p, 'usep', 2368.0, 8768.0, 270.000, 'usep' )
    set u = BlzCreateUnitWithSkin( p, 'uaod', 3680.0, 9696.0, 270.000, 'uaod' )
    set u = BlzCreateUnitWithSkin( p, 'uzg1', 3680.0, 8160.0, 270.000, 'uzg1' )
    set u = BlzCreateUnitWithSkin( p, 'uzg1', 3488.0, 7904.0, 270.000, 'uzg1' )
    set u = BlzCreateUnitWithSkin( p, 'uzg1', 2272.0, 7712.0, 270.000, 'uzg1' )
    set u = BlzCreateUnitWithSkin( p, 'uzg1', 2080.0, 8096.0, 270.000, 'uzg1' )
    set u = BlzCreateUnitWithSkin( p, 'uzg1', 2016.0, 7840.0, 270.000, 'uzg1' )
    set u = BlzCreateUnitWithSkin( p, 'uzg2', 4000.0, 8864.0, 270.000, 'uzg2' )
    set u = BlzCreateUnitWithSkin( p, 'ubon', 2432.0, 9344.0, 270.000, 'ubon' )
    set u = BlzCreateUnitWithSkin( p, 'utom', 3072.0, 4224.0, 270.000, 'utom' )
    set u = BlzCreateUnitWithSkin( p, 'ugrv', 3136.0, 10176.0, 270.000, 'ugrv' )
    set u = BlzCreateUnitWithSkin( p, 'usap', 2432.0, 10176.0, 270.000, 'usap' )
    set u = CreateBlightedGoldmine( p, 4032.0, 9280.0, 270.000 )
    call SetResourceAmount( u, 12500 )
endfunction

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'unec', -4133.9, 6856.5, 342.993, 'unec' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', 1608.0, 10071.0, 356.682, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', 1346.3, 4090.2, 206.417, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', 1877.4, 10062.7, 73.567, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', 1784.9, 10049.6, 142.409, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', 1781.0, 9986.8, 282.951, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', 1770.5, 9882.0, 183.214, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', 916.6, 4201.4, 126.050, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', 1445.6, 9986.9, 54.010, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', 2192.3, 4737.5, 339.070, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uaco', 3598.0, 9137.9, 77.972, 'uaco' )
    set u = BlzCreateUnitWithSkin( p, 'uaco', 3782.8, 9409.7, 249.123, 'uaco' )
    set u = BlzCreateUnitWithSkin( p, 'uaco', 3809.7, 9368.4, 263.922, 'uaco' )
    set u = BlzCreateUnitWithSkin( p, 'uaco', 3776.7, 9230.2, 330.226, 'uaco' )
    set u = BlzCreateUnitWithSkin( p, 'uaco', 3738.1, 9155.3, 105.615, 'uaco' )
    set u = BlzCreateUnitWithSkin( p, 'uaco', 3710.1, 9045.8, 112.317, 'uaco' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', 3393.7, 8311.5, 266.350, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', 2916.9, 8914.9, 339.400, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', 2456.2, 8346.6, 169.502, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', 2870.6, 7936.2, 189.465, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -3947.3, 5787.5, 228.292, 'unec' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -4634.4, 6612.7, 81.027, 'unec' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -4606.2, 6946.2, 325.238, 'unec' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -4380.3, 6456.6, 215.789, 'unec' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', -4478.8, 6765.1, 82.125, 'hrif' )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
    call CreateBuildingsForPlayer0(  )
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0(  )
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreatePlayerBuildings(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: Melee Initialization
//
// Default melee game initialization for all players
//===========================================================================
function Trig_Melee_Initialization_Actions takes nothing returns nothing
    call MeleeStartingVisibility(  )
    call MeleeStartingHeroLimit(  )
    call MeleeGrantHeroItems(  )
    call MeleeStartingResources(  )
    call MeleeClearExcessUnits(  )
    call MeleeStartingUnits(  )
    call MeleeStartingAI(  )
    call MeleeInitVictoryDefeat(  )
    call BlzShowTerrain( false )
endfunction

//===========================================================================
function InitTrig_Melee_Initialization takes nothing returns nothing
    set gg_trg_Melee_Initialization = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Melee_Initialization, function Trig_Melee_Initialization_Actions )
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_Melee_Initialization(  )
endfunction

//===========================================================================
function RunInitializationTriggers takes nothing returns nothing
    call ConditionalTriggerExecute( gg_trg_Melee_Initialization )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), true )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_002
    call SetPlayerTeam( Player(0), 0 )

endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds( -12800.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -14208.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 12672.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 13568.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -12800.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 13568.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 12672.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -14208.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "LordaeronSummerDay" )
    call SetAmbientNightSound( "LordaeronSummerNight" )
    call SetMapMusic( "Music", true, 0 )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )
    call InitCustomTriggers(  )
    call RunInitializationTriggers(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "Just another Warcraft III map" )
    call SetMapDescription( "Nondescript" )
    call SetPlayers( 1 )
    call SetTeams( 1 )
    call SetGamePlacement( MAP_PLACEMENT_USE_MAP_SETTINGS )

    call DefineStartLocation( 0, -4352.0, 6144.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call SetPlayerSlotAvailable( Player(0), MAP_CONTROL_USER )
    call InitGenericPlayerSlots(  )
endfunction

