//===========================================================================
// 
// Just another Warcraft III map
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Map Author: Unknown
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
    // User-defined
    integer                 udg_cnt                    = 0

    // Generated
    rect                    gg_rct_battle_field        = null
    camerasetup             gg_cam_Camera_001          = null
    camerasetup             gg_cam_Camera_002          = null
    camerasetup             gg_cam_Camera_003          = null
    camerasetup             gg_cam_Camera_004          = null
    camerasetup             gg_cam_Camera_005          = null
    trigger                 gg_trg_Melee_Initialization = null
    trigger                 gg_trg_camera              = null
    trigger                 gg_trg_fight               = null
endglobals

function InitGlobals takes nothing returns nothing
    set udg_cnt = 0
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'hsor', 5117.9, 6526.9, 62.064, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hsor', 3592.8, -1920.3, 299.211, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hsor', 3172.2, -1996.7, 298.859, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hsor', 3358.8, -1764.1, 227.951, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 3544.0, -1642.2, 157.944, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 3367.5, -1553.8, 25.423, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'ogru', 1896.7, -1706.1, 326.708, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'ogru', 1854.8, -1905.5, 338.805, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'ogru', 1825.6, -2120.1, 352.650, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'ogru', 4260.7, -2595.3, 79.675, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'ogru', -5356.6, -9513.4, 279.743, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'orai', -5363.7, -9309.8, 273.975, 'orai' )
    set u = BlzCreateUnitWithSkin( p, 'otau', -5252.1, -9485.4, 286.702, 'otau' )
    set u = BlzCreateUnitWithSkin( p, 'okod', -4945.5, -8813.0, 273.295, 'okod' )
    set u = BlzCreateUnitWithSkin( p, 'otbk', -5238.6, -9271.0, 283.322, 'otbk' )
    set u = BlzCreateUnitWithSkin( p, 'odoc', -5244.0, -9091.9, 281.889, 'odoc' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'oshm', -5396.0, -8756.2, 273.432, 'oshm' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'ospw', -5115.1, -9315.3, 271.961, 'ospw' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'ogru', -5117.3, -9470.3, 270.464, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'owyv', -5374.0, -8705.5, 286.367, 'owyv' )
    set u = BlzCreateUnitWithSkin( p, 'otbr', -4700.6, -8776.4, 278.293, 'otbr' )
    set u = BlzCreateUnitWithSkin( p, 'ocat', -5355.0, -8872.5, 272.312, 'ocat' )
    set u = BlzCreateUnitWithSkin( p, 'nw2w', -5133.2, -9091.8, 282.445, 'nw2w' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'ogru', -4997.0, -9483.9, 277.008, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'orai', -5004.0, -9280.3, 276.118, 'orai' )
    set u = BlzCreateUnitWithSkin( p, 'otau', -4892.4, -9455.9, 283.080, 'otau' )
    set u = BlzCreateUnitWithSkin( p, 'okod', -4780.1, -8834.3, 274.996, 'okod' )
    set u = BlzCreateUnitWithSkin( p, 'otbk', -4878.9, -9241.5, 280.268, 'otbk' )
    set u = BlzCreateUnitWithSkin( p, 'odoc', -4884.3, -9062.4, 279.205, 'odoc' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'oshm', -5010.3, -9081.2, 275.480, 'oshm' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'ospw', -4755.4, -9285.8, 274.818, 'ospw' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'ogru', -4757.6, -9440.8, 275.654, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'owyv', -5193.7, -8753.6, 274.436, 'owyv' )
    set u = BlzCreateUnitWithSkin( p, 'otbr', -5023.7, -8720.6, 275.080, 'otbr' )
    set u = BlzCreateUnitWithSkin( p, 'ocat', -5137.3, -8870.9, 274.119, 'ocat' )
    set u = BlzCreateUnitWithSkin( p, 'nw2w', -4773.5, -9062.3, 274.789, 'nw2w' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'ogru', -4648.0, -9472.0, 271.775, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'orai', -4655.1, -9268.4, 271.792, 'orai' )
    set u = BlzCreateUnitWithSkin( p, 'otau', -4543.5, -9444.0, 269.225, 'otau' )
    set u = BlzCreateUnitWithSkin( p, 'okod', -4438.1, -8803.2, 271.145, 'okod' )
    set u = BlzCreateUnitWithSkin( p, 'otbk', -4530.0, -9229.6, 273.747, 'otbk' )
    set u = BlzCreateUnitWithSkin( p, 'odoc', -4535.4, -9050.5, 273.580, 'odoc' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'oshm', -4661.3, -9069.3, 271.792, 'oshm' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'ospw', -4406.5, -9273.9, 270.192, 'ospw' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'ogru', -4408.7, -9428.9, 270.279, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'owyv', -4496.4, -8795.8, 271.221, 'owyv' )
    set u = BlzCreateUnitWithSkin( p, 'otbr', -4289.0, -8829.0, 271.143, 'otbr' )
    set u = BlzCreateUnitWithSkin( p, 'ocat', -4594.9, -8813.5, 271.362, 'ocat' )
    set u = BlzCreateUnitWithSkin( p, 'nw2w', -4424.6, -9050.3, 270.652, 'nw2w' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'ogru', -4289.2, -9457.3, 266.396, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'orai', -4296.3, -9253.7, 266.975, 'orai' )
    set u = BlzCreateUnitWithSkin( p, 'otau', -4184.7, -9429.3, 263.128, 'otau' )
    set u = BlzCreateUnitWithSkin( p, 'okod', -4088.5, -8835.6, 262.543, 'okod' )
    set u = BlzCreateUnitWithSkin( p, 'otbk', -4171.2, -9215.0, 263.477, 'otbk' )
    set u = BlzCreateUnitWithSkin( p, 'odoc', -4176.6, -9035.9, 264.149, 'odoc' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'oshm', -4302.5, -9054.7, 267.419, 'oshm' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'ospw', -4047.7, -9259.2, 266.188, 'ospw' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'ogru', -4049.9, -9414.2, 265.993, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'owyv', -3929.1, -8849.4, 266.593, 'owyv' )
    set u = BlzCreateUnitWithSkin( p, 'otbr', -4087.6, -8871.6, 262.410, 'otbr' )
    set u = BlzCreateUnitWithSkin( p, 'ocat', -4287.6, -8816.4, 267.319, 'ocat' )
    set u = BlzCreateUnitWithSkin( p, 'nw2w', -4065.8, -9035.7, 266.870, 'nw2w' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'ogru', -3919.4, -9469.2, 269.771, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'orai', -3926.5, -9265.6, 270.035, 'orai' )
    set u = BlzCreateUnitWithSkin( p, 'otau', -3814.9, -9441.2, 265.874, 'otau' )
    set u = BlzCreateUnitWithSkin( p, 'okod', -3718.6, -8847.5, 264.445, 'okod' )
    set u = BlzCreateUnitWithSkin( p, 'otbk', -3801.4, -9226.9, 265.938, 'otbk' )
    set u = BlzCreateUnitWithSkin( p, 'odoc', -3806.8, -9047.8, 266.475, 'odoc' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'oshm', -3932.7, -9066.6, 270.219, 'oshm' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'ospw', -3677.8, -9271.1, 261.726, 'ospw' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'ogru', -3680.0, -9426.1, 260.990, 'ogru' )
    set u = BlzCreateUnitWithSkin( p, 'owyv', -3782.7, -8843.1, 269.351, 'owyv' )
    set u = BlzCreateUnitWithSkin( p, 'otbr', -4848.1, -8750.7, 264.327, 'otbr' )
    set u = BlzCreateUnitWithSkin( p, 'ocat', -3917.8, -8828.3, 269.796, 'ocat' )
    set u = BlzCreateUnitWithSkin( p, 'nw2w', -3695.9, -9047.6, 263.206, 'nw2w' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'Othr', -4660.8, -9870.4, 253.746, 'Othr' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 690 )
    set u = BlzCreateUnitWithSkin( p, 'Orex', -4406.8, -9780.3, 259.985, 'Orex' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 540 )
    set u = BlzCreateUnitWithSkin( p, 'onzg', -4903.0, -9803.9, 255.639, 'onzg' )
    set u = BlzCreateUnitWithSkin( p, 'Osam', -5519.7, -9278.8, 285.460, 'Osam' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 540 )
    call SelectHeroSkill( u, 'AOwk' )
    call SelectHeroSkill( u, 'AOwk' )
    call SelectHeroSkill( u, 'AOwk' )
    call SelectHeroSkill( u, 'AOmi' )
    call SelectHeroSkill( u, 'AOmi' )
    call SelectHeroSkill( u, 'AOmi' )
    call SelectHeroSkill( u, 'AOcr' )
    call SelectHeroSkill( u, 'AOcr' )
    call SelectHeroSkill( u, 'AOcr' )
    call SelectHeroSkill( u, 'AOww' )
    set u = BlzCreateUnitWithSkin( p, 'Usyl', -4120.1, -9778.9, 278.720, 'Usyl' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 570 )
endfunction

//===========================================================================
function CreateUnitsForPlayer3 takes nothing returns nothing
    local player p = Player(3)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'nzof', -5600.6, -11617.8, 110.338, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -5366.2, -11495.8, 119.957, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -3515.4, -12071.4, 131.832, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -5236.5, -11496.5, 123.876, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -5008.4, -11338.8, 98.147, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -4901.5, -11777.0, 99.306, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -5406.6, -11792.5, 114.166, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -4909.1, -11608.1, 99.875, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -5438.4, -11940.4, 111.519, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -5519.8, -11549.1, 114.031, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -5155.4, -11230.9, 132.246, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -4809.6, -11423.6, 103.931, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -5051.3, -11586.1, 95.870, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -4742.1, -11068.5, 109.667, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -5156.8, -11846.1, 120.144, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -5719.9, -11817.7, 104.340, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -4750.7, -11822.7, 102.933, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -5134.8, -12031.1, 118.174, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -5309.8, -11722.1, 117.907, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -4957.0, -11472.5, 99.134, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -5295.3, -11373.3, 124.632, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5124.6, -11419.5, 94.068, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5507.7, -11705.2, 112.255, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5724.7, -11502.0, 107.290, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5440.5, -11427.1, 118.785, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4935.5, -11229.8, 101.254, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5134.9, -11700.9, 122.967, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5319.4, -11921.6, 114.942, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5020.0, -11824.8, 96.045, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4838.9, -11661.2, 101.547, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'ugar', -5465.7, -11765.3, 112.776, 'ugar' )
    set u = BlzCreateUnitWithSkin( p, 'ugar', -4814.0, -11777.6, 101.576, 'ugar' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -3839.9, -11470.7, 110.347, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -6308.6, -11703.8, 104.442, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'ufro', -5092.0, -11681.5, 94.459, 'ufro' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -6074.2, -11581.8, 112.831, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -5944.5, -11582.5, 98.081, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'uban', -4986.8, -12067.6, 96.219, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uban', -5046.6, -11881.1, 95.217, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uban', -5338.0, -11580.5, 119.336, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uban', -4839.2, -11542.4, 102.240, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uban', -5594.6, -11790.3, 108.555, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -5716.4, -11424.8, 108.590, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -5609.5, -11863.0, 107.375, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -4657.2, -11389.7, 108.790, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -4422.8, -11267.7, 117.035, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -4293.1, -11268.4, 93.725, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -4065.0, -11110.7, 107.829, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -3958.1, -11548.9, 107.057, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -4463.2, -11564.4, 112.311, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -3965.7, -11380.1, 108.137, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -4495.0, -11712.3, 110.082, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -4576.4, -11321.0, 111.919, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -4212.0, -11002.9, 104.443, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -3866.2, -11195.6, 112.280, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -4107.9, -11358.0, 104.766, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -3798.7, -10840.4, 118.531, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -4213.4, -11618.0, 100.763, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -4776.6, -11589.6, 103.706, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -4027.5, -11723.3, 104.420, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -3807.4, -11594.6, 110.058, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -4191.4, -11803.1, 100.477, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -4366.4, -11494.0, 115.562, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -4013.6, -11244.4, 108.047, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -3924.8, -10961.3, 113.344, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4181.3, -11191.4, 103.950, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4564.4, -11477.1, 110.540, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4781.3, -11273.9, 106.080, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4497.1, -11199.0, 115.873, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -3992.1, -11001.7, 110.969, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4191.5, -11472.8, 101.989, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4376.0, -11693.5, 113.124, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4076.6, -11596.8, 104.041, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4050.1, -11451.1, 105.572, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -3885.6, -11648.0, 107.972, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'ugar', -4522.4, -11537.2, 111.055, 'ugar' )
    set u = BlzCreateUnitWithSkin( p, 'ugar', -4609.2, -11551.6, 108.601, 'ugar' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -6114.6, -11878.5, 108.523, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -5617.1, -11694.2, 108.876, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'ugar', -3775.1, -10938.5, 117.747, 'ugar' )
    set u = BlzCreateUnitWithSkin( p, 'ugar', -4098.2, -11157.0, 106.512, 'ugar' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -6146.4, -12026.4, 106.475, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'ufro', -4148.7, -11453.4, 103.152, 'ufro' )
    set u = BlzCreateUnitWithSkin( p, 'ufro', -3849.9, -11802.5, 107.677, 'ufro' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -6227.8, -11635.1, 107.546, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uban', -4043.5, -11839.5, 103.466, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uban', -4103.3, -11653.1, 103.123, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uban', -4394.7, -11352.4, 116.631, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uban', -3895.8, -11314.3, 110.397, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uban', -4651.2, -11562.2, 107.367, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'Udea', -4393.0, -10996.2, 122.410, 'Udea' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 495 )
    call SelectHeroSkill( u, 'AUdc' )
    call SelectHeroSkill( u, 'AUdc' )
    call SelectHeroSkill( u, 'AUdc' )
    call SelectHeroSkill( u, 'AUdp' )
    call SelectHeroSkill( u, 'AUdp' )
    call SelectHeroSkill( u, 'AUdp' )
    call SelectHeroSkill( u, 'AUau' )
    call SelectHeroSkill( u, 'AUau' )
    call SelectHeroSkill( u, 'AUau' )
    call SelectHeroSkill( u, 'AUan' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -5408.5, -11317.3, 122.110, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -5759.3, -11672.1, 104.267, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4694.6, -11700.9, 105.140, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -5864.8, -11932.1, 99.018, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -5678.9, -12037.4, 103.911, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -6017.8, -11808.1, 94.516, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -5665.0, -11558.5, 108.821, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -4439.1, -11789.6, 110.730, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -4439.6, -11106.8, 119.028, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -4309.9, -11107.6, 93.543, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -4593.2, -11160.1, 113.462, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -4228.8, -10842.0, 105.271, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -4513.9, -11038.2, 117.876, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uban', -4411.4, -11191.6, 118.490, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -6003.3, -11459.3, 96.320, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5832.6, -11505.5, 103.041, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -6215.7, -11791.2, 106.482, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -6148.5, -11513.1, 111.397, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5643.5, -11315.8, 113.229, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5842.9, -11786.9, 100.534, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -6027.4, -12007.6, 93.743, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5728.0, -11910.9, 103.370, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'ugar', -6173.8, -11851.3, 107.152, 'ugar' )
    set u = BlzCreateUnitWithSkin( p, 'ufro', -5800.0, -11767.5, 102.102, 'ufro' )
    set u = BlzCreateUnitWithSkin( p, 'uban', -5754.7, -11967.2, 102.179, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uban', -6046.0, -11666.5, 112.616, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uban', -6302.6, -11876.3, 103.363, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -6630.6, -11832.8, 93.910, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -6402.5, -11675.1, 101.708, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -6295.7, -12113.3, 102.117, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -6303.3, -11944.5, 102.902, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -6549.6, -11567.2, 97.400, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -6445.4, -11922.4, 99.056, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -6365.1, -12287.7, 99.585, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -6351.2, -11808.8, 102.407, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uske', -6518.8, -11755.8, 97.597, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -6329.7, -11566.1, 104.923, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -6529.1, -12037.2, 96.302, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'ufro', -6486.2, -12017.8, 97.533, 'ufro' )
    set u = BlzCreateUnitWithSkin( p, 'nzof', -6376.7, -12503.4, 98.533, 'nzof' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -5784.4, -12224.5, 99.926, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -6236.5, -11464.6, 109.092, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -5931.5, -12116.6, 96.293, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5711.5, -12115.4, 102.487, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -6117.5, -11445.8, 113.284, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -5268.0, -12011.8, 115.179, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -5461.4, -12173.1, 108.672, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -3595.7, -10676.2, 118.984, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -3676.7, -10941.7, 112.606, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -3659.9, -11102.6, 111.246, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -3431.8, -10944.9, 119.378, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -3578.9, -10837.0, 116.904, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -3474.7, -11192.1, 115.060, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -3580.3, -11452.1, 109.944, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -3733.2, -11328.2, 114.112, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uske', -3548.1, -11025.5, 115.182, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -3558.3, -11306.9, 111.788, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -3742.9, -11527.6, 112.006, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -3416.9, -11285.2, 115.394, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'ugar', -3465.0, -10991.1, 117.847, 'ugar' )
    set u = BlzCreateUnitWithSkin( p, 'ufro', -3515.5, -11287.5, 113.025, 'ufro' )
    set u = BlzCreateUnitWithSkin( p, 'uban', -3470.1, -11487.2, 112.150, 'uban' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -3323.1, -11291.8, 117.468, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -3255.5, -10936.6, 123.917, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -3470.5, -11340.7, 113.552, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'unec', -3381.6, -11057.6, 119.052, 'unec' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'uske', -3448.9, -11097.9, 116.842, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'ugar', -3231.9, -11034.7, 122.952, 'ugar' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -3226.0, -11127.4, 121.752, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -3133.5, -11038.0, 125.110, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -3116.8, -11198.8, 123.137, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -3511.1, -10880.4, 118.194, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'ucry', -3334.8, -10872.1, 123.015, 'ucry' )
    set u = BlzCreateUnitWithSkin( p, 'nzom', -3075.3, -10697.8, 132.406, 'nzom' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -3118.2, -10945.1, 126.929, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uske', -3191.6, -10778.5, 128.178, 'uske' )
    set u = BlzCreateUnitWithSkin( p, 'ugar', -3108.5, -10744.1, 130.751, 'ugar' )
    set u = BlzCreateUnitWithSkin( p, 'Udea', -3983.6, -10803.0, 111.579, 'Udea' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 495 )
    call SelectHeroSkill( u, 'AUdc' )
    call SelectHeroSkill( u, 'AUdc' )
    call SelectHeroSkill( u, 'AUdc' )
    call SelectHeroSkill( u, 'AUdp' )
    call SelectHeroSkill( u, 'AUdp' )
    call SelectHeroSkill( u, 'AUdp' )
    call SelectHeroSkill( u, 'AUau' )
    call SelectHeroSkill( u, 'AUau' )
    call SelectHeroSkill( u, 'AUau' )
    call SelectHeroSkill( u, 'AUan' )
    set u = BlzCreateUnitWithSkin( p, 'Uanb', -4630.9, -10907.5, 116.153, 'Uanb' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 420 )
    call SelectHeroSkill( u, 'AUim' )
    call SelectHeroSkill( u, 'AUim' )
    call SelectHeroSkill( u, 'AUim' )
    call SelectHeroSkill( u, 'AUts' )
    call SelectHeroSkill( u, 'AUts' )
    call SelectHeroSkill( u, 'AUts' )
    call SelectHeroSkill( u, 'AUcb' )
    call SelectHeroSkill( u, 'AUcb' )
    call SelectHeroSkill( u, 'AUcb' )
    call IssueImmediateOrder( u, "Carrionscarabsoff" )
    call SelectHeroSkill( u, 'AUls' )
    set u = BlzCreateUnitWithSkin( p, 'Uktl', -4934.8, -11052.2, 102.656, 'Uktl' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 750 )
    call SelectHeroSkill( u, 'AUfn' )
    call SelectHeroSkill( u, 'AUfn' )
    call SelectHeroSkill( u, 'AUfn' )
    call SelectHeroSkill( u, 'AUfu' )
    call SelectHeroSkill( u, 'AUfu' )
    call SelectHeroSkill( u, 'AUfu' )
    call IssueImmediateOrder( u, "frostarmoroff" )
    call SelectHeroSkill( u, 'AUdr' )
    call SelectHeroSkill( u, 'AUdr' )
    call SelectHeroSkill( u, 'AUdr' )
    call SelectHeroSkill( u, 'AUdd' )
    set u = BlzCreateUnitWithSkin( p, 'Udea', -5883.6, -11365.3, 104.050, 'Udea' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 495 )
    call SelectHeroSkill( u, 'AUdc' )
    call SelectHeroSkill( u, 'AUdc' )
    call SelectHeroSkill( u, 'AUdc' )
    call SelectHeroSkill( u, 'AUdp' )
    call SelectHeroSkill( u, 'AUdp' )
    call SelectHeroSkill( u, 'AUdp' )
    call SelectHeroSkill( u, 'AUau' )
    call SelectHeroSkill( u, 'AUau' )
    call SelectHeroSkill( u, 'AUau' )
    call SelectHeroSkill( u, 'AUan' )
    set u = BlzCreateUnitWithSkin( p, 'ubdd', -4911.8, -11286.2, 115.520, 'ubdd' )
    set u = BlzCreateUnitWithSkin( p, 'uktn', -5897.7, 10942.9, 292.005, 'uktn' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -6029.7, 10754.4, 343.410, 'unec' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -5733.3, 10738.6, 135.693, 'unec' )
    set u = BlzCreateUnitWithSkin( p, 'ugho', -5963.2, 10413.1, 233.105, 'ugho' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -5592.9, 9585.3, 151.278, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -6108.4, 9952.3, 310.145, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'uabo', -6034.3, 9559.8, 41.993, 'uabo' )
    set u = BlzCreateUnitWithSkin( p, 'Ulic', -5852.5, 9814.9, 266.356, 'Ulic' )
endfunction

//===========================================================================
function CreateUnitsForPlayer9 takes nothing returns nothing
    local player p = Player(9)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'Hmgd', -6391.4, -10483.0, 292.700, 'Hmgd' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 495 )
    call SelectHeroSkill( u, 'AHhb' )
    call SelectHeroSkill( u, 'AHhb' )
    call SelectHeroSkill( u, 'AHhb' )
    call SelectHeroSkill( u, 'AHds' )
    call SelectHeroSkill( u, 'AHds' )
    call SelectHeroSkill( u, 'AHds' )
    call SelectHeroSkill( u, 'AHad' )
    call SelectHeroSkill( u, 'AHad' )
    call SelectHeroSkill( u, 'AHad' )
    call SelectHeroSkill( u, 'AHre' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -7090.9, -10821.1, 303.444, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -7160.1, -10711.4, 303.406, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', -7241.7, -10562.7, 303.224, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hmpr', -7314.8, -10453.5, 303.240, 'hmpr' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -7017.7, -10757.7, 302.081, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -7086.9, -10648.0, 302.085, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hsor', -7249.7, -10378.3, 302.018, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hspt', -7166.2, -10485.8, 301.836, 'hspt' )
    call SetUnitState( u, UNIT_STATE_MANA, 250 )
    set u = BlzCreateUnitWithSkin( p, 'hgry', -7322.1, -10355.1, 302.637, 'hgry' )
    set u = BlzCreateUnitWithSkin( p, 'hmtt', -7273.1, -10141.8, 300.729, 'hmtt' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6938.7, -10690.4, 300.630, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -7007.9, -10580.7, 300.679, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', -7006.3, -10348.4, 299.111, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hmpr', -7162.6, -10322.8, 300.698, 'hmpr' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6865.6, -10627.0, 299.289, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6934.7, -10517.3, 299.379, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hsor', -7097.6, -10247.6, 299.501, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hspt', -7084.5, -10409.9, 300.400, 'hspt' )
    call SetUnitState( u, UNIT_STATE_MANA, 250 )
    set u = BlzCreateUnitWithSkin( p, 'hmtm', -6715.5, -9838.5, 302.916, 'hmtm' )
    set u = BlzCreateUnitWithSkin( p, 'hdhw', -7061.6, -10371.1, 299.886, 'hdhw' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6782.9, -10570.2, 303.444, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6852.1, -10460.5, 303.406, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', -6933.7, -10311.8, 303.224, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hmpr', -7006.8, -10202.5, 303.240, 'hmpr' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6709.8, -10506.8, 302.081, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6778.9, -10397.1, 302.085, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hsor', -6941.8, -10127.4, 302.018, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hspt', -6858.3, -10234.9, 301.836, 'hspt' )
    call SetUnitState( u, UNIT_STATE_MANA, 250 )
    set u = BlzCreateUnitWithSkin( p, 'hgry', -7014.1, -10104.1, 302.637, 'hgry' )
    set u = BlzCreateUnitWithSkin( p, 'hmtt', -7071.6, -10002.7, 300.729, 'hmtt' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6630.8, -10439.5, 300.630, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6700.0, -10329.8, 300.679, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', -6698.4, -10097.4, 299.111, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hmpr', -6854.7, -10071.8, 300.698, 'hmpr' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6557.6, -10376.1, 299.289, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6626.8, -10266.4, 299.379, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hsor', -6789.6, -9996.7, 299.501, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hspt', -6776.6, -10159.0, 300.400, 'hspt' )
    call SetUnitState( u, UNIT_STATE_MANA, 250 )
    set u = BlzCreateUnitWithSkin( p, 'hmtm', -6913.2, -9905.1, 297.436, 'hmtm' )
    set u = BlzCreateUnitWithSkin( p, 'hdhw', -6753.6, -10120.2, 299.886, 'hdhw' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6479.2, -10291.3, 303.444, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6548.4, -10181.6, 303.406, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', -6630.0, -10032.9, 303.224, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hmpr', -6703.1, -9923.6, 303.240, 'hmpr' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6406.0, -10227.9, 302.081, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6475.2, -10118.1, 302.085, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hsor', -6638.0, -9848.5, 302.018, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hspt', -6554.5, -9956.0, 301.836, 'hspt' )
    call SetUnitState( u, UNIT_STATE_MANA, 250 )
    set u = BlzCreateUnitWithSkin( p, 'hgry', -6710.4, -9825.2, 302.637, 'hgry' )
    set u = BlzCreateUnitWithSkin( p, 'hmtt', -6661.4, -9612.0, 300.729, 'hmtt' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6327.0, -10160.6, 300.630, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6396.2, -10050.9, 300.679, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', -6394.6, -9818.5, 299.111, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hmpr', -6550.9, -9792.9, 300.698, 'hmpr' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6253.9, -10097.2, 299.289, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6323.0, -9987.5, 299.379, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hsor', -6485.9, -9717.8, 299.501, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hspt', -6472.8, -9880.1, 300.400, 'hspt' )
    call SetUnitState( u, UNIT_STATE_MANA, 250 )
    set u = BlzCreateUnitWithSkin( p, 'hmtm', -6819.9, -9696.8, 302.916, 'hmtm' )
    set u = BlzCreateUnitWithSkin( p, 'hdhw', -6449.9, -9841.3, 299.886, 'hdhw' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6171.2, -10040.4, 303.444, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6240.4, -9930.7, 303.406, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', -6322.0, -9782.0, 303.224, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hmpr', -6395.1, -9672.7, 303.240, 'hmpr' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6098.1, -9977.0, 302.081, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6167.2, -9867.2, 302.085, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hsor', -6330.1, -9597.6, 302.018, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hspt', -6246.6, -9705.1, 301.836, 'hspt' )
    call SetUnitState( u, UNIT_STATE_MANA, 250 )
    set u = BlzCreateUnitWithSkin( p, 'hgry', -6402.4, -9574.3, 302.637, 'hgry' )
    set u = BlzCreateUnitWithSkin( p, 'hmtt', -6459.9, -9472.9, 300.729, 'hmtt' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -6019.1, -9909.7, 300.630, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6088.3, -9800.0, 300.679, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', -6086.7, -9567.6, 299.111, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hmpr', -6243.0, -9542.0, 300.698, 'hmpr' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', -5945.9, -9846.3, 299.289, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', -6015.1, -9736.5, 299.379, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hsor', -6177.9, -9466.9, 299.501, 'hsor' )
    call SetUnitState( u, UNIT_STATE_MANA, 200 )
    set u = BlzCreateUnitWithSkin( p, 'hspt', -6164.9, -9629.2, 300.400, 'hspt' )
    call SetUnitState( u, UNIT_STATE_MANA, 250 )
    set u = BlzCreateUnitWithSkin( p, 'hmtm', -6301.5, -9375.3, 297.436, 'hmtm' )
    set u = BlzCreateUnitWithSkin( p, 'hdhw', -6141.9, -9590.4, 299.886, 'hdhw' )
    call SetUnitState( u, UNIT_STATE_MANA, 300 )
    set u = BlzCreateUnitWithSkin( p, 'Hjai', -6171.1, -10300.0, 320.320, 'Hjai' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 705 )
    call SelectHeroSkill( u, 'AHbz' )
    call SelectHeroSkill( u, 'AHbz' )
    call SelectHeroSkill( u, 'AHbz' )
    call SelectHeroSkill( u, 'AHwe' )
    call SelectHeroSkill( u, 'AHwe' )
    call SelectHeroSkill( u, 'AHwe' )
    call SelectHeroSkill( u, 'AHab' )
    call SelectHeroSkill( u, 'AHab' )
    call SelectHeroSkill( u, 'AHab' )
    call SelectHeroSkill( u, 'AHmt' )
    set u = BlzCreateUnitWithSkin( p, 'Hmbr', -6594.4, -10677.6, 335.900, 'Hmbr' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 420 )
    call SelectHeroSkill( u, 'AHtb' )
    call SelectHeroSkill( u, 'AHtb' )
    call SelectHeroSkill( u, 'AHtb' )
    call SelectHeroSkill( u, 'AHtc' )
    call SelectHeroSkill( u, 'AHtc' )
    call SelectHeroSkill( u, 'AHtc' )
    call SelectHeroSkill( u, 'AHbh' )
    call SelectHeroSkill( u, 'AHbh' )
    call SelectHeroSkill( u, 'AHbh' )
    call SelectHeroSkill( u, 'AHav' )
    set u = BlzCreateUnitWithSkin( p, 'Hdgo', -5439.1, -10239.0, 305.955, 'Hdgo' )
    call SetHeroLevel( u, 10, false )
    call SetUnitState( u, UNIT_STATE_MANA, 495 )
    call SelectHeroSkill( u, 'AHhb' )
    call SelectHeroSkill( u, 'AHhb' )
    call SelectHeroSkill( u, 'AHhb' )
    call SelectHeroSkill( u, 'AHds' )
    call SelectHeroSkill( u, 'AHds' )
    call SelectHeroSkill( u, 'AHds' )
    call SelectHeroSkill( u, 'AHad' )
    call SelectHeroSkill( u, 'AHad' )
    call SelectHeroSkill( u, 'AHad' )
    call SelectHeroSkill( u, 'AHre' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 12629.9, 13446.3, 310.439, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 12514.5, 13338.3, 270.700, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', 12698.8, 13658.2, 284.649, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hmtm', 13554.3, 12918.8, 201.211, 'hmtm' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 9042.1, 16643.4, 290.555, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 8858.3, 16246.1, 32.590, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 9352.9, 16143.6, 129.529, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 10594.1, 15108.1, 267.198, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 10768.3, 15106.0, 267.198, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 11158.2, 15109.4, 267.198, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 11443.9, 15121.2, 267.198, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 10585.0, 14521.6, 93.587, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 10796.6, 14521.6, 86.107, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 11133.6, 14517.9, 86.107, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 11408.8, 14499.6, 86.107, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 11726.5, 14777.3, 177.154, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 10416.2, 14921.0, 337.987, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', 10923.9, 15541.0, 274.642, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 11240.5, 15550.6, 267.047, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hmpr', 12092.6, 15306.9, 227.953, 'hmpr' )
    set u = BlzCreateUnitWithSkin( p, 'hsor', 12209.4, 15078.3, 236.200, 'hsor' )
    set u = BlzCreateUnitWithSkin( p, 'Hamg', 13007.5, 14319.8, 267.291, 'Hamg' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 13590.9, 14078.7, 151.759, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 13995.4, 13812.0, 215.272, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 13791.5, 13693.6, 29.206, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 13916.6, 14728.5, 59.976, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 14004.4, 14304.2, 71.446, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 14039.1, 15433.8, 63.690, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 15183.9, 16044.9, 139.487, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 14219.1, 16646.2, 251.547, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 15310.1, 16960.8, 227.835, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 13537.2, 17760.0, 329.519, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 13970.6, 17838.7, 257.539, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 14054.2, 17351.8, 127.855, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hkni', 13728.0, 17312.6, 52.448, 'hkni' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 13241.8, 17276.4, 343.406, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 13233.8, 16925.2, 14.292, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 10580.6, 15964.1, 298.042, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 10974.7, 15962.3, 267.504, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 11317.5, 15975.1, 241.805, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', 9650.0, 16945.0, 287.146, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 8415.8, 15299.9, 174.259, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hfoo', 8684.4, 15414.5, 335.093, 'hfoo' )
    set u = BlzCreateUnitWithSkin( p, 'hrif', 8559.9, 15695.7, 189.190, 'hrif' )
    set u = BlzCreateUnitWithSkin( p, 'hmtm', 7863.1, 17203.7, 114.801, 'hmtm' )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0(  )
    call CreateUnitsForPlayer3(  )
    call CreateUnitsForPlayer9(  )
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreatePlayerBuildings(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Regions
//*
//***************************************************************************

function CreateRegions takes nothing returns nothing
    local weathereffect we

    set gg_rct_battle_field = Rect( -8320.0, -13440.0, -2272.0, -7744.0 )
endfunction

//***************************************************************************
//*
//*  Cameras
//*
//***************************************************************************

function CreateCameras takes nothing returns nothing

    set gg_cam_Camera_001 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_ROTATION, 295.7, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_ANGLE_OF_ATTACK, 356.9, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_TARGET_DISTANCE, 4831.5, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_FARZ, 10000.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_NEARZ, 16.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Camera_001, -4689.6, -11968.9, 0.0 )

    set gg_cam_Camera_002 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_ROTATION, 110.6, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_ANGLE_OF_ATTACK, 312.2, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_TARGET_DISTANCE, 5846.2, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_FARZ, 10000.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_NEARZ, 16.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_002, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Camera_002, -5081.1, -10513.5, 0.0 )

    set gg_cam_Camera_003 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_ROTATION, 178.7, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_ANGLE_OF_ATTACK, 356.7, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_TARGET_DISTANCE, 1272.3, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_FARZ, 10000.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_NEARZ, 16.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_003, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Camera_003, -6490.3, -10065.5, 0.0 )

    set gg_cam_Camera_004 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_ROTATION, 64.7, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_ANGLE_OF_ATTACK, 343.9, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_TARGET_DISTANCE, 1693.4, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_FARZ, 10000.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_NEARZ, 16.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Camera_004, -4643.1, -9267.7, 0.0 )

    set gg_cam_Camera_005 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_ROTATION, 310.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_ANGLE_OF_ATTACK, 311.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_TARGET_DISTANCE, 4392.3, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_FARZ, 10000.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_NEARZ, 16.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_005, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Camera_005, -5576.9, -10421.0, 0.0 )

endfunction

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: Melee Initialization
//
// Default melee game initialization for all players
//===========================================================================
function Trig_Melee_Initialization_Actions takes nothing returns nothing
    call MeleeStartingVisibility(  )
    call BlzShowTerrain( false )
    call CreateFogModifierRectBJ( true, Player(0), FOG_OF_WAR_VISIBLE, GetPlayableMapRect() )
    call PanCameraToTimedLocForPlayer( Player(0), GetRectCenter(GetPlayableMapRect()), 0 )
    call CinematicModeBJ( true, GetPlayersAll() )
    call CinematicFadeBJ( bj_CINEFADETYPE_FADEOUT, 0.00, "ReplaceableTextures\\CameraMasks\\White_mask.blp", 0, 0, 0, 0 )
    call PolledWait( 0.50 )
    call CinematicModeExBJ( false, GetPlayersAll(), 0.50 )
    call CinematicFadeBJ( bj_CINEFADETYPE_FADEIN, 0.00, "ReplaceableTextures\\CameraMasks\\White_mask.blp", 0, 0, 0, 0 )
    call CameraSetupApplyForPlayer( true, gg_cam_Camera_001, Player(0), 0 )
endfunction

//===========================================================================
function InitTrig_Melee_Initialization takes nothing returns nothing
    set gg_trg_Melee_Initialization = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Melee_Initialization, function Trig_Melee_Initialization_Actions )
endfunction

//===========================================================================
// Trigger: camera
//===========================================================================
function Trig_camera_Func002C takes nothing returns boolean
    if ( not ( udg_cnt >= 4 ) ) then
        return false
    endif
    return true
endfunction

function Trig_camera_Func003C takes nothing returns boolean
    if ( not ( udg_cnt == 0 ) ) then
        return false
    endif
    return true
endfunction

function Trig_camera_Func004C takes nothing returns boolean
    if ( not ( udg_cnt == 1 ) ) then
        return false
    endif
    return true
endfunction

function Trig_camera_Func005C takes nothing returns boolean
    if ( not ( udg_cnt == 2 ) ) then
        return false
    endif
    return true
endfunction

function Trig_camera_Func006C takes nothing returns boolean
    if ( not ( udg_cnt == 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_camera_Actions takes nothing returns nothing
    set udg_cnt = ( udg_cnt + 1 )
    if ( Trig_camera_Func002C() ) then
        set udg_cnt = 0
    else
    endif
    if ( Trig_camera_Func003C() ) then
        call CameraSetupApplyForPlayer( true, gg_cam_Camera_001, Player(0), 1.00 )
    else
    endif
    if ( Trig_camera_Func004C() ) then
        call CameraSetupApplyForPlayer( true, gg_cam_Camera_002, Player(0), 1.00 )
    else
    endif
    if ( Trig_camera_Func005C() ) then
        call CameraSetupApplyForPlayer( true, gg_cam_Camera_003, Player(0), 1.00 )
    else
    endif
    if ( Trig_camera_Func006C() ) then
        call CameraSetupApplyForPlayer( true, gg_cam_Camera_004, Player(0), 1.00 )
    else
    endif
endfunction

//===========================================================================
function InitTrig_camera takes nothing returns nothing
    set gg_trg_camera = CreateTrigger(  )
    call TriggerRegisterPlayerEventEndCinematic( gg_trg_camera, Player(0) )
    call TriggerAddAction( gg_trg_camera, function Trig_camera_Actions )
endfunction

//===========================================================================
// Trigger: fight
//===========================================================================
function Trig_fight_Func005A takes nothing returns nothing
    call SetUnitAcquireRangeBJ( GetEnumUnit(), 999999.00 )
    call RemoveGuardPosition( GetEnumUnit() )
    call IssuePointOrderLocBJ( GetEnumUnit(), "attack", GetRectCenter(gg_rct_battle_field) )
endfunction

function Trig_fight_Actions takes nothing returns nothing
    call SetPlayerAllianceStateBJ( Player(0), Player(3), bj_ALLIANCE_UNALLIED_VISION )
    call SetPlayerAllianceStateBJ( Player(9), Player(3), bj_ALLIANCE_UNALLIED_VISION )
    call SetPlayerAllianceStateBJ( Player(3), Player(0), bj_ALLIANCE_UNALLIED_VISION )
    call SetPlayerAllianceStateBJ( Player(3), Player(9), bj_ALLIANCE_UNALLIED_VISION )
    call ForGroupBJ( GetUnitsInRectAll(gg_rct_battle_field), function Trig_fight_Func005A )
endfunction

//===========================================================================
function InitTrig_fight takes nothing returns nothing
    set gg_trg_fight = CreateTrigger(  )
    call TriggerRegisterPlayerChatEvent( gg_trg_fight, Player(0), "fight", true )
    call TriggerAddAction( gg_trg_fight, function Trig_fight_Actions )
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_Melee_Initialization(  )
    call InitTrig_camera(  )
    call InitTrig_fight(  )
endfunction

//===========================================================================
function RunInitializationTriggers takes nothing returns nothing
    call ConditionalTriggerExecute( gg_trg_Melee_Initialization )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call ForcePlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_ORC )
    call SetPlayerRaceSelectable( Player(0), false )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

    // Player 3
    call SetPlayerStartLocation( Player(3), 1 )
    call ForcePlayerStartLocation( Player(3), 1 )
    call SetPlayerColor( Player(3), ConvertPlayerColor(3) )
    call SetPlayerRacePreference( Player(3), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(3), false )
    call SetPlayerController( Player(3), MAP_CONTROL_COMPUTER )

    // Player 9
    call SetPlayerStartLocation( Player(9), 2 )
    call ForcePlayerStartLocation( Player(9), 2 )
    call SetPlayerColor( Player(9), ConvertPlayerColor(9) )
    call SetPlayerRacePreference( Player(9), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(9), false )
    call SetPlayerController( Player(9), MAP_CONTROL_COMPUTER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_002
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerTeam( Player(3), 0 )
    call SetPlayerTeam( Player(9), 0 )

    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(9), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(9), true )
    call SetPlayerAllianceStateAllyBJ( Player(9), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(9), Player(3), true )

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(9), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(9), Player(3), true )

endfunction

function InitAllyPriorities takes nothing returns nothing

    call SetStartLocPrioCount( 1, 2 )
    call SetStartLocPrio( 1, 0, 2, MAP_LOC_PRIO_LOW )

    call SetEnemyStartLocPrioCount( 1, 1 )

    call SetStartLocPrioCount( 2, 2 )
    call SetStartLocPrio( 2, 0, 1, MAP_LOC_PRIO_LOW )

    call SetEnemyStartLocPrioCount( 2, 1 )
    call SetEnemyStartLocPrio( 2, 0, 1, MAP_LOC_PRIO_LOW )
endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    local weathereffect we
    call SetCameraBounds( -15360.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -22016.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 15360.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 21504.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -15360.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 21504.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 15360.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -22016.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl" )
    call SetTerrainFogEx( 0, 3000.0, 100000.0, 0.500, 0.000, 0.000, 1.000 )
    set we = AddWeatherEffect( Rect(-16128.0,-22528.0,16128.0,22528.0), 'SNls' )
    call EnableWeatherEffect( we, true )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "LordaeronSummerDay" )
    call SetAmbientNightSound( "LordaeronSummerNight" )
    call SetMapMusic( "Music", true, 0 )
    call CreateRegions(  )
    call CreateCameras(  )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )
    call InitCustomTriggers(  )
    call RunInitializationTriggers(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_931" )
    call SetMapDescription( "TRIGSTR_933" )
    call SetPlayers( 3 )
    call SetTeams( 3 )
    call SetGamePlacement( MAP_PLACEMENT_USE_MAP_SETTINGS )

    call DefineStartLocation( 0, -4608.0, -9792.0 )
    call DefineStartLocation( 1, -5120.0, -11200.0 )
    call DefineStartLocation( 2, -6144.0, -10304.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call InitCustomTeams(  )
    call InitAllyPriorities(  )
endfunction

