udg_registered_unit = nil
gg_rct_Unit_experiments = nil
gg_cam_Camera_001 = nil
gg_cam_Camera_002 = nil
gg_cam_Camera_003 = nil
gg_cam_Camera_004 = nil
gg_cam_Camera_005 = nil
gg_snd_ir_frozenthrone_07 = ""
gg_trg_Melee_Initialization = nil
gg_trg_Camera_constant = nil
gg_trg_Unit_register = nil
gg_unit_H001_0052 = nil
gg_unit_H004_0000 = nil
function InitGlobals()
end

function InitSounds()
gg_snd_ir_frozenthrone_07 = "Sounds/ir_frozenthrone_07.mp3"
end

function CreateUnitsForPlayer0()
local p = Player(0)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("orai"), 988.6, -476.4, 133.084, FourCC("orai"))
u = BlzCreateUnitWithSkin(p, FourCC("orai"), 543.8, -1353.5, 109.075, FourCC("orai"))
u = BlzCreateUnitWithSkin(p, FourCC("orai"), 1161.7, -872.4, 128.944, FourCC("orai"))
u = BlzCreateUnitWithSkin(p, FourCC("orai"), 1052.0, -720.3, 129.270, FourCC("orai"))
u = BlzCreateUnitWithSkin(p, FourCC("ogru"), 1184.7, -605.3, 134.829, FourCC("ogru"))
u = BlzCreateUnitWithSkin(p, FourCC("ogru"), 826.5, -445.6, 129.242, FourCC("ogru"))
u = BlzCreateUnitWithSkin(p, FourCC("ogru"), 737.4, -720.0, 120.666, FourCC("ogru"))
u = BlzCreateUnitWithSkin(p, FourCC("ogru"), 779.8, -912.9, 118.711, FourCC("ogru"))
u = BlzCreateUnitWithSkin(p, FourCC("ogru"), 1298.1, -1195.3, 126.564, FourCC("ogru"))
u = BlzCreateUnitWithSkin(p, FourCC("otau"), 1351.9, -655.2, 137.259, FourCC("otau"))
u = BlzCreateUnitWithSkin(p, FourCC("otau"), 898.0, -780.6, 124.151, FourCC("otau"))
u = BlzCreateUnitWithSkin(p, FourCC("otau"), 971.3, -1127.4, 118.476, FourCC("otau"))
u = BlzCreateUnitWithSkin(p, FourCC("otau"), 604.4, -1082.8, 111.572, FourCC("otau"))
u = BlzCreateUnitWithSkin(p, FourCC("ohun"), 637.7, -1464.1, 108.809, FourCC("ohun"))
u = BlzCreateUnitWithSkin(p, FourCC("ohun"), 727.1, -1216.6, 113.376, FourCC("ohun"))
u = BlzCreateUnitWithSkin(p, FourCC("ohun"), 1192.6, -1067.7, 126.333, FourCC("ohun"))
u = BlzCreateUnitWithSkin(p, FourCC("ohun"), 909.9, -1307.0, 116.774, FourCC("ohun"))
u = BlzCreateUnitWithSkin(p, FourCC("oshm"), 1139.2, -384.0, 139.192, FourCC("oshm"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("oshm"), 490.0, -1191.1, 113.207, FourCC("oshm"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("oshm"), 901.2, -1565.9, 114.507, FourCC("oshm"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("oshm"), 1093.1, -1258.8, 121.451, FourCC("oshm"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("odoc"), 642.0, -1623.9, 42.628, FourCC("odoc"))
u = BlzCreateUnitWithSkin(p, FourCC("odoc"), 1306.5, -928.9, 158.834, FourCC("odoc"))
u = BlzCreateUnitWithSkin(p, FourCC("okod"), 1099.6, -1496.7, 118.712, FourCC("okod"))
u = BlzCreateUnitWithSkin(p, FourCC("okod"), 1037.3, -916.6, 124.713, FourCC("okod"))
u = BlzCreateUnitWithSkin(p, FourCC("Obla"), 441.7, -1051.9, 107.140, FourCC("Obla"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 2895)
SelectHeroSkill(u, FourCC("AOwk"))
SelectHeroSkill(u, FourCC("AOwk"))
SelectHeroSkill(u, FourCC("AOwk"))
SelectHeroSkill(u, FourCC("AOmi"))
SelectHeroSkill(u, FourCC("AOmi"))
SelectHeroSkill(u, FourCC("AOmi"))
SelectHeroSkill(u, FourCC("AOcr"))
SelectHeroSkill(u, FourCC("AOcr"))
SelectHeroSkill(u, FourCC("AOcr"))
SelectHeroSkill(u, FourCC("AOww"))
u = BlzCreateUnitWithSkin(p, FourCC("Ofar"), 536.8, -885.7, 111.900, FourCC("Ofar"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 3840)
SelectHeroSkill(u, FourCC("AOcl"))
SelectHeroSkill(u, FourCC("AOcl"))
SelectHeroSkill(u, FourCC("AOcl"))
SelectHeroSkill(u, FourCC("AOfs"))
SelectHeroSkill(u, FourCC("AOfs"))
SelectHeroSkill(u, FourCC("AOfs"))
SelectHeroSkill(u, FourCC("AOsf"))
SelectHeroSkill(u, FourCC("AOsf"))
SelectHeroSkill(u, FourCC("AOsf"))
SelectHeroSkill(u, FourCC("AOeq"))
u = BlzCreateUnitWithSkin(p, FourCC("Otch"), 622.3, -705.5, 117.300, FourCC("Otch"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 1740)
SelectHeroSkill(u, FourCC("AOsh"))
SelectHeroSkill(u, FourCC("AOsh"))
SelectHeroSkill(u, FourCC("AOsh"))
SelectHeroSkill(u, FourCC("AOws"))
SelectHeroSkill(u, FourCC("AOws"))
SelectHeroSkill(u, FourCC("AOws"))
SelectHeroSkill(u, FourCC("AOae"))
SelectHeroSkill(u, FourCC("AOae"))
SelectHeroSkill(u, FourCC("AOae"))
SelectHeroSkill(u, FourCC("AOre"))
u = BlzCreateUnitWithSkin(p, FourCC("Oshd"), 685.2, -500.7, 123.380, FourCC("Oshd"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 3210)
SelectHeroSkill(u, FourCC("AOhw"))
SelectHeroSkill(u, FourCC("AOhw"))
SelectHeroSkill(u, FourCC("AOhw"))
SelectHeroSkill(u, FourCC("AOhx"))
SelectHeroSkill(u, FourCC("AOhx"))
SelectHeroSkill(u, FourCC("AOhx"))
SelectHeroSkill(u, FourCC("AOsw"))
SelectHeroSkill(u, FourCC("AOsw"))
SelectHeroSkill(u, FourCC("AOsw"))
SelectHeroSkill(u, FourCC("AOvd"))
u = BlzCreateUnitWithSkin(p, FourCC("odoc"), 898.4, -284.2, 172.293, FourCC("odoc"))
u = BlzCreateUnitWithSkin(p, FourCC("odoc"), 785.5, -1044.8, 143.024, FourCC("odoc"))
u = BlzCreateUnitWithSkin(p, FourCC("okod"), 754.6, -1313.2, 115.727, FourCC("okod"))
end

function CreateBuildingsForPlayer1()
local p = Player(1)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("eaoe"), 241.0, -2046.8, 96.972, FourCC("eaoe"))
IssueImmediateOrder(u, "unroot")
u = BlzCreateUnitWithSkin(p, FourCC("eaom"), -105.9, -2145.4, 89.725, FourCC("eaom"))
IssueImmediateOrder(u, "unroot")
u = BlzCreateUnitWithSkin(p, FourCC("etoe"), -549.8, -2085.8, 80.608, FourCC("etoe"))
IssueImmediateOrder(u, "unroot")
u = BlzCreateUnitWithSkin(p, FourCC("etrp"), 473.2, -1864.9, 102.534, FourCC("etrp"))
IssueImmediateOrder(u, "unroot")
u = BlzCreateUnitWithSkin(p, FourCC("eden"), -318.0, -2434.4, 85.856, FourCC("eden"))
IssueImmediateOrder(u, "unroot")
u = BlzCreateUnitWithSkin(p, FourCC("eaow"), 206.7, -2392.0, 99.224, FourCC("eaow"))
IssueImmediateOrder(u, "unroot")
end

function CreateUnitsForPlayer1()
local p = Player(1)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("emtg"), -1290.6, -1529.4, 42.603, FourCC("emtg"))
u = BlzCreateUnitWithSkin(p, FourCC("emtg"), -337.6, -1723.6, 81.820, FourCC("emtg"))
u = BlzCreateUnitWithSkin(p, FourCC("esen"), -626.6, -1447.3, 75.674, FourCC("esen"))
u = BlzCreateUnitWithSkin(p, FourCC("esen"), -1044.1, -1378.5, 76.841, FourCC("esen"))
u = BlzCreateUnitWithSkin(p, FourCC("esen"), -896.5, -1630.4, 80.317, FourCC("esen"))
u = BlzCreateUnitWithSkin(p, FourCC("earc"), -260.7, -1524.4, 85.634, FourCC("earc"))
u = BlzCreateUnitWithSkin(p, FourCC("earc"), -788.5, -1335.5, 89.717, FourCC("earc"))
u = BlzCreateUnitWithSkin(p, FourCC("earc"), 100.7, -1626.3, 94.787, FourCC("earc"))
u = BlzCreateUnitWithSkin(p, FourCC("edoc"), 72.3, -1375.5, 94.581, FourCC("edoc"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("edot"), -851.6, -1464.9, 84.713, FourCC("edot"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("edot"), -33.7, -1825.7, 91.342, FourCC("edot"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("edot"), 362.2, -1529.3, 101.631, FourCC("edot"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("efdr"), 239.3, -1877.7, 97.390, FourCC("efdr"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("efdr"), -266.9, -2010.2, 86.288, FourCC("efdr"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("ehpr"), -443.3, -1341.1, 80.147, FourCC("ehpr"))
u = BlzCreateUnitWithSkin(p, FourCC("echm"), -121.2, -1935.5, 89.368, FourCC("echm"))
u = BlzCreateUnitWithSkin(p, FourCC("echm"), -805.5, -1839.1, 78.502, FourCC("echm"))
u = BlzCreateUnitWithSkin(p, FourCC("edcm"), 342.7, -1406.3, 98.590, FourCC("edcm"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("edcm"), -203.3, -1379.9, 86.916, FourCC("edcm"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("Ekee"), -452.5, -1134.5, 78.770, FourCC("Ekee"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 3465)
SelectHeroSkill(u, FourCC("AEer"))
SelectHeroSkill(u, FourCC("AEer"))
SelectHeroSkill(u, FourCC("AEer"))
SelectHeroSkill(u, FourCC("AEfn"))
SelectHeroSkill(u, FourCC("AEfn"))
SelectHeroSkill(u, FourCC("AEfn"))
SelectHeroSkill(u, FourCC("AEah"))
SelectHeroSkill(u, FourCC("AEah"))
SelectHeroSkill(u, FourCC("AEah"))
SelectHeroSkill(u, FourCC("AEtq"))
u = BlzCreateUnitWithSkin(p, FourCC("Emoo"), -252.6, -1137.5, 84.960, FourCC("Emoo"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 3300)
SelectHeroSkill(u, FourCC("AEst"))
SelectHeroSkill(u, FourCC("AEst"))
SelectHeroSkill(u, FourCC("AEst"))
SelectHeroSkill(u, FourCC("AHfa"))
SelectHeroSkill(u, FourCC("AHfa"))
SelectHeroSkill(u, FourCC("AHfa"))
SelectHeroSkill(u, FourCC("AEar"))
SelectHeroSkill(u, FourCC("AEar"))
SelectHeroSkill(u, FourCC("AEar"))
SelectHeroSkill(u, FourCC("AEsf"))
u = BlzCreateUnitWithSkin(p, FourCC("Edem"), -40.0, -1150.9, 91.640, FourCC("Edem"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 2715)
SelectHeroSkill(u, FourCC("AEmb"))
SelectHeroSkill(u, FourCC("AEmb"))
SelectHeroSkill(u, FourCC("AEmb"))
SelectHeroSkill(u, FourCC("AEim"))
SelectHeroSkill(u, FourCC("AEim"))
SelectHeroSkill(u, FourCC("AEim"))
SelectHeroSkill(u, FourCC("AEev"))
SelectHeroSkill(u, FourCC("AEev"))
SelectHeroSkill(u, FourCC("AEev"))
SelectHeroSkill(u, FourCC("AEme"))
u = BlzCreateUnitWithSkin(p, FourCC("Ewar"), 195.0, -1125.7, 99.050, FourCC("Ewar"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 2595)
SelectHeroSkill(u, FourCC("AEfk"))
SelectHeroSkill(u, FourCC("AEfk"))
SelectHeroSkill(u, FourCC("AEfk"))
SelectHeroSkill(u, FourCC("AEbl"))
SelectHeroSkill(u, FourCC("AEbl"))
SelectHeroSkill(u, FourCC("AEbl"))
SelectHeroSkill(u, FourCC("AEsh"))
SelectHeroSkill(u, FourCC("AEsh"))
SelectHeroSkill(u, FourCC("AEsh"))
SelectHeroSkill(u, FourCC("AEsv"))
end

function CreateUnitsForPlayer4()
local p = Player(4)
local u
local unitID
local t
local life

gg_unit_H001_0052 = BlzCreateUnitWithSkin(p, FourCC("H001"), -87.4, 1379.2, 270.000, FourCC("H001"))
SetHeroLevel(gg_unit_H001_0052, 80, false)
SetUnitState(gg_unit_H001_0052, UNIT_STATE_MANA, 4170)
UnitAddItemToSlotById(gg_unit_H001_0052, FourCC("I000"), 0)
end

function CreateUnitsForPlayer9()
local p = Player(9)
local u
local unitID
local t
local life

gg_unit_H004_0000 = BlzCreateUnitWithSkin(p, FourCC("H004"), -125.1, -388.6, 88.970, FourCC("H004"))
SetHeroLevel(gg_unit_H004_0000, 80, false)
SetUnitState(gg_unit_H004_0000, UNIT_STATE_MANA, 2385)
SelectHeroSkill(gg_unit_H004_0000, FourCC("AHhb"))
SelectHeroSkill(gg_unit_H004_0000, FourCC("AHhb"))
SelectHeroSkill(gg_unit_H004_0000, FourCC("AHhb"))
SelectHeroSkill(gg_unit_H004_0000, FourCC("AHds"))
SelectHeroSkill(gg_unit_H004_0000, FourCC("AHds"))
SelectHeroSkill(gg_unit_H004_0000, FourCC("AHds"))
SelectHeroSkill(gg_unit_H004_0000, FourCC("AHad"))
SelectHeroSkill(gg_unit_H004_0000, FourCC("AHad"))
SelectHeroSkill(gg_unit_H004_0000, FourCC("AHad"))
SelectHeroSkill(gg_unit_H004_0000, FourCC("AHre"))
u = BlzCreateUnitWithSkin(p, FourCC("U002"), 190.5, -652.7, 95.770, FourCC("U002"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 2385)
SelectHeroSkill(u, FourCC("AUdc"))
SelectHeroSkill(u, FourCC("AUdc"))
SelectHeroSkill(u, FourCC("AUdc"))
SelectHeroSkill(u, FourCC("AUdp"))
SelectHeroSkill(u, FourCC("AUdp"))
SelectHeroSkill(u, FourCC("AUdp"))
SelectHeroSkill(u, FourCC("AUau"))
SelectHeroSkill(u, FourCC("AUau"))
SelectHeroSkill(u, FourCC("AUau"))
SelectHeroSkill(u, FourCC("AUan"))
u = BlzCreateUnitWithSkin(p, FourCC("Hjai"), -394.9, -609.6, 82.240, FourCC("Hjai"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 4065)
SelectHeroSkill(u, FourCC("AHbz"))
SelectHeroSkill(u, FourCC("AHbz"))
SelectHeroSkill(u, FourCC("AHbz"))
SelectHeroSkill(u, FourCC("AHwe"))
SelectHeroSkill(u, FourCC("AHwe"))
SelectHeroSkill(u, FourCC("AHwe"))
SelectHeroSkill(u, FourCC("AHab"))
SelectHeroSkill(u, FourCC("AHab"))
SelectHeroSkill(u, FourCC("AHab"))
SelectHeroSkill(u, FourCC("AHmt"))
u = BlzCreateUnitWithSkin(p, FourCC("hcth"), -1248.0, -998.7, 55.446, FourCC("hcth"))
u = BlzCreateUnitWithSkin(p, FourCC("hcth"), -1125.3, -1228.7, 61.573, FourCC("hcth"))
u = BlzCreateUnitWithSkin(p, FourCC("hcth"), -948.3, -1206.8, 68.547, FourCC("hcth"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -1304.4, -828.5, 51.208, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -1423.3, -559.3, 42.946, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -592.1, -1188.5, 65.551, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -523.3, -1850.2, 77.318, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -1531.2, -877.4, 47.256, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -1307.9, -1207.3, 57.208, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -698.1, -1580.6, 70.233, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hcth"), -1106.3, -1518.1, 65.232, FourCC("hcth"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), -1413.2, -1036.7, 52.416, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), -1452.4, -1282.5, 55.270, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), -953.2, -1958.0, 65.084, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), -805.1, -2167.3, 76.089, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hmpr"), -1501.4, -1477.6, 56.847, FourCC("hmpr"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("hmpr"), -1261.4, -1710.4, 61.311, FourCC("hmpr"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("hmpr"), -751.3, -1763.6, 73.773, FourCC("hmpr"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("hsor"), -1208.3, -2003.4, 67.414, FourCC("hsor"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("hsor"), -1525.0, -1884.4, 60.805, FourCC("hsor"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("hsor"), -280.9, -1908.1, 50.313, FourCC("hsor"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("hspt"), -1729.7, -1420.8, 52.059, FourCC("hspt"))
SetUnitState(u, UNIT_STATE_MANA, 250)
u = BlzCreateUnitWithSkin(p, FourCC("hgry"), -1840.2, -1251.6, 47.850, FourCC("hgry"))
u = BlzCreateUnitWithSkin(p, FourCC("hgry"), -1447.7, -1966.7, 62.879, FourCC("hgry"))
u = BlzCreateUnitWithSkin(p, FourCC("hgry"), -1661.6, -906.9, 45.309, FourCC("hgry"))
u = BlzCreateUnitWithSkin(p, FourCC("hsor"), -1583.8, -1712.5, 58.055, FourCC("hsor"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("hsor"), -1327.7, -1902.9, 64.434, FourCC("hsor"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("hsor"), -1767.0, -1054.2, 45.991, FourCC("hsor"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("hdhw"), -1297.7, -1544.4, 44.467, FourCC("hdhw"))
SetUnitState(u, UNIT_STATE_MANA, 300)
u = BlzCreateUnitWithSkin(p, FourCC("Hpal"), -1169.2, -692.9, 51.880, FourCC("Hpal"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 2385)
SelectHeroSkill(u, FourCC("AHhb"))
SelectHeroSkill(u, FourCC("AHhb"))
SelectHeroSkill(u, FourCC("AHhb"))
SelectHeroSkill(u, FourCC("AHds"))
SelectHeroSkill(u, FourCC("AHds"))
SelectHeroSkill(u, FourCC("AHds"))
SelectHeroSkill(u, FourCC("AHad"))
SelectHeroSkill(u, FourCC("AHad"))
SelectHeroSkill(u, FourCC("AHad"))
SelectHeroSkill(u, FourCC("AHre"))
u = BlzCreateUnitWithSkin(p, FourCC("Hamg"), -1114.6, -882.0, 56.790, FourCC("Hamg"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 4065)
SelectHeroSkill(u, FourCC("AHbz"))
SelectHeroSkill(u, FourCC("AHbz"))
SelectHeroSkill(u, FourCC("AHbz"))
SelectHeroSkill(u, FourCC("AHwe"))
SelectHeroSkill(u, FourCC("AHwe"))
SelectHeroSkill(u, FourCC("AHwe"))
SelectHeroSkill(u, FourCC("AHab"))
SelectHeroSkill(u, FourCC("AHab"))
SelectHeroSkill(u, FourCC("AHab"))
SelectHeroSkill(u, FourCC("AHmt"))
u = BlzCreateUnitWithSkin(p, FourCC("Hmkg"), -959.8, -1013.8, 62.870, FourCC("Hmkg"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 1995)
SelectHeroSkill(u, FourCC("AHtb"))
SelectHeroSkill(u, FourCC("AHtb"))
SelectHeroSkill(u, FourCC("AHtb"))
SelectHeroSkill(u, FourCC("AHtc"))
SelectHeroSkill(u, FourCC("AHtc"))
SelectHeroSkill(u, FourCC("AHtc"))
SelectHeroSkill(u, FourCC("AHbh"))
SelectHeroSkill(u, FourCC("AHbh"))
SelectHeroSkill(u, FourCC("AHbh"))
SelectHeroSkill(u, FourCC("AHav"))
u = BlzCreateUnitWithSkin(p, FourCC("Hblm"), -810.0, -1155.9, 68.640, FourCC("Hblm"))
SetHeroLevel(u, 80, false)
SetUnitState(u, UNIT_STATE_MANA, 3840)
SelectHeroSkill(u, FourCC("AHfs"))
SelectHeroSkill(u, FourCC("AHfs"))
SelectHeroSkill(u, FourCC("AHfs"))
SelectHeroSkill(u, FourCC("AHbn"))
SelectHeroSkill(u, FourCC("AHbn"))
SelectHeroSkill(u, FourCC("AHbn"))
SelectHeroSkill(u, FourCC("AHdr"))
SelectHeroSkill(u, FourCC("AHdr"))
SelectHeroSkill(u, FourCC("AHdr"))
SelectHeroSkill(u, FourCC("AHpx"))
u = BlzCreateUnitWithSkin(p, FourCC("hmpr"), -1615.4, -1075.8, 33.795, FourCC("hmpr"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("hmpr"), -523.5, -1639.7, 81.659, FourCC("hmpr"))
SetUnitState(u, UNIT_STATE_MANA, 200)
end

function CreatePlayerBuildings()
CreateBuildingsForPlayer1()
end

function CreatePlayerUnits()
CreateUnitsForPlayer0()
CreateUnitsForPlayer1()
CreateUnitsForPlayer4()
CreateUnitsForPlayer9()
end

function CreateAllUnits()
CreatePlayerBuildings()
CreatePlayerUnits()
end

function CreateRegions()
local we

gg_rct_Unit_experiments = Rect(-4096.0, -4096.0, -3936.0, -3936.0)
end

function CreateCameras()
gg_cam_Camera_001 = CreateCameraSetup()
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ROTATION, 170.4, 0.0)
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ANGLE_OF_ATTACK, 327.7, 0.0)
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_TARGET_DISTANCE, 405.4, 0.0)
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ROLL, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_FIELD_OF_VIEW, 90.0, 0.0)
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_FARZ, 10000.0, 0.0)
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_NEARZ, 16.0, 0.0)
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
CameraSetupSetDestPosition(gg_cam_Camera_001, 3488.8, -1384.8, 0.0)
gg_cam_Camera_002 = CreateCameraSetup()
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_ROTATION, 65.4, 0.0)
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_ANGLE_OF_ATTACK, 322.4, 0.0)
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_TARGET_DISTANCE, 2479.3, 0.0)
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_ROLL, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_FIELD_OF_VIEW, 90.0, 0.0)
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_FARZ, 10000.0, 0.0)
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_NEARZ, 16.0, 0.0)
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_002, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
CameraSetupSetDestPosition(gg_cam_Camera_002, -573.6, -2000.2, 0.0)
gg_cam_Camera_003 = CreateCameraSetup()
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_ROTATION, 271.4, 0.0)
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_ANGLE_OF_ATTACK, 333.3, 0.0)
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_TARGET_DISTANCE, 1693.4, 0.0)
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_ROLL, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_FIELD_OF_VIEW, 90.0, 0.0)
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_FARZ, 10000.0, 0.0)
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_NEARZ, 16.0, 0.0)
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_003, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
CameraSetupSetDestPosition(gg_cam_Camera_003, 59.1, -520.8, 0.0)
gg_cam_Camera_004 = CreateCameraSetup()
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_ROTATION, 92.7, 0.0)
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_ANGLE_OF_ATTACK, 335.4, 0.0)
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_TARGET_DISTANCE, 2049.0, 0.0)
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_ROLL, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_FIELD_OF_VIEW, 90.0, 0.0)
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_FARZ, 10000.0, 0.0)
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_NEARZ, 16.0, 0.0)
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_004, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
CameraSetupSetDestPosition(gg_cam_Camera_004, -193.4, -1039.7, 0.0)
gg_cam_Camera_005 = CreateCameraSetup()
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_ROTATION, 91.1, 0.0)
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_ANGLE_OF_ATTACK, 344.2, 0.0)
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_TARGET_DISTANCE, 1051.5, 0.0)
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_ROLL, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_FIELD_OF_VIEW, 90.0, 0.0)
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_FARZ, 10000.0, 0.0)
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_NEARZ, 16.0, 0.0)
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
CameraSetupSetField(gg_cam_Camera_005, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
CameraSetupSetDestPosition(gg_cam_Camera_005, -90.8, 2001.0, 0.0)
end

function Trig_Melee_Initialization_Actions()
BlzShowTerrain(false)
SetSkyModel("Environment\\Sky\\FelwoodSky\\FelwoodSky.mdl")
BlzShowSkyBox(true)
PlayMusicBJ(gg_snd_ir_frozenthrone_07)
SetMusicVolumeBJ(100)
end

function InitTrig_Melee_Initialization()
gg_trg_Melee_Initialization = CreateTrigger()
TriggerAddAction(gg_trg_Melee_Initialization, Trig_Melee_Initialization_Actions)
end

function Trig_Camera_constant_Actions()
SetCameraFieldForPlayer(Player(4), CAMERA_FIELD_FARZ, 100000000.00, 0)
end

function InitTrig_Camera_constant()
gg_trg_Camera_constant = CreateTrigger()
TriggerRegisterTimerEventPeriodic(gg_trg_Camera_constant, 0.01)
TriggerAddAction(gg_trg_Camera_constant, Trig_Camera_constant_Actions)
end

function Trig_Unit_register_Actions()
udg_registered_unit = gg_unit_H001_0052
udg_registered_unit = gg_unit_H004_0000
end

function InitTrig_Unit_register()
gg_trg_Unit_register = CreateTrigger()
TriggerAddAction(gg_trg_Unit_register, Trig_Unit_register_Actions)
end

function InitCustomTriggers()
InitTrig_Melee_Initialization()
InitTrig_Camera_constant()
InitTrig_Unit_register()
end

function RunInitializationTriggers()
ConditionalTriggerExecute(gg_trg_Melee_Initialization)
ConditionalTriggerExecute(gg_trg_Unit_register)
end

function InitCustomPlayerSlots()
SetPlayerStartLocation(Player(0), 0)
ForcePlayerStartLocation(Player(0), 0)
SetPlayerColor(Player(0), ConvertPlayerColor(0))
SetPlayerRacePreference(Player(0), RACE_PREF_ORC)
SetPlayerRaceSelectable(Player(0), false)
SetPlayerController(Player(0), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(1), 1)
ForcePlayerStartLocation(Player(1), 1)
SetPlayerColor(Player(1), ConvertPlayerColor(1))
SetPlayerRacePreference(Player(1), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(1), false)
SetPlayerController(Player(1), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(2), 2)
ForcePlayerStartLocation(Player(2), 2)
SetPlayerColor(Player(2), ConvertPlayerColor(2))
SetPlayerRacePreference(Player(2), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(2), false)
SetPlayerController(Player(2), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(4), 3)
SetPlayerColor(Player(4), ConvertPlayerColor(4))
SetPlayerRacePreference(Player(4), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(4), false)
SetPlayerController(Player(4), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(9), 4)
ForcePlayerStartLocation(Player(9), 4)
SetPlayerColor(Player(9), ConvertPlayerColor(9))
SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(9), false)
SetPlayerController(Player(9), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
SetPlayerTeam(Player(4), 0)
SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(0), 1)
SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(1), 1)
SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(2), 1)
SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(9), 1)
SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(2), true)
SetPlayerAllianceStateControlBJ(Player(0), Player(1), true)
SetPlayerAllianceStateControlBJ(Player(0), Player(2), true)
SetPlayerAllianceStateControlBJ(Player(0), Player(9), true)
SetPlayerAllianceStateControlBJ(Player(1), Player(0), true)
SetPlayerAllianceStateControlBJ(Player(1), Player(2), true)
SetPlayerAllianceStateControlBJ(Player(1), Player(9), true)
SetPlayerAllianceStateControlBJ(Player(2), Player(0), true)
SetPlayerAllianceStateControlBJ(Player(2), Player(1), true)
SetPlayerAllianceStateControlBJ(Player(2), Player(9), true)
SetPlayerAllianceStateControlBJ(Player(9), Player(0), true)
SetPlayerAllianceStateControlBJ(Player(9), Player(1), true)
SetPlayerAllianceStateControlBJ(Player(9), Player(2), true)
SetPlayerAllianceStateFullControlBJ(Player(0), Player(1), true)
SetPlayerAllianceStateFullControlBJ(Player(0), Player(2), true)
SetPlayerAllianceStateFullControlBJ(Player(0), Player(9), true)
SetPlayerAllianceStateFullControlBJ(Player(1), Player(0), true)
SetPlayerAllianceStateFullControlBJ(Player(1), Player(2), true)
SetPlayerAllianceStateFullControlBJ(Player(1), Player(9), true)
SetPlayerAllianceStateFullControlBJ(Player(2), Player(0), true)
SetPlayerAllianceStateFullControlBJ(Player(2), Player(1), true)
SetPlayerAllianceStateFullControlBJ(Player(2), Player(9), true)
SetPlayerAllianceStateFullControlBJ(Player(9), Player(0), true)
SetPlayerAllianceStateFullControlBJ(Player(9), Player(1), true)
SetPlayerAllianceStateFullControlBJ(Player(9), Player(2), true)
end

function InitAllyPriorities()
SetStartLocPrioCount(0, 3)
SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(0, 1, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(0, 4)
SetEnemyStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(0, 1, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(0, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(1, 1)
SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(1, 2)
SetEnemyStartLocPrio(1, 0, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(1, 1, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(2, 4)
SetStartLocPrio(2, 0, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(2, 1, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(2, 2, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(2, 4)
SetEnemyStartLocPrio(2, 0, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(2, 1, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(2, 2, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(4, 1)
SetStartLocPrio(4, 0, 3, MAP_LOC_PRIO_LOW)
end

function main()
SetCameraBounds(-4096.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -4096.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 4096.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 4096.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -4096.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 4096.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 4096.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -4096.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
SetTerrainFogEx(0, 100000.0, 100000.0, 0.000, 0.000, 0.000, 0.000)
NewSoundEnvironment("Default")
SetAmbientDaySound("IceCrownDay")
SetAmbientNightSound("IceCrownNight")
SetMapMusic("Music", true, 0)
InitSounds()
CreateRegions()
CreateCameras()
CreateAllUnits()
InitBlizzard()
InitGlobals()
InitCustomTriggers()
RunInitializationTriggers()
end

function config()
SetMapName("TRIGSTR_005")
SetMapDescription("TRIGSTR_007")
SetPlayers(5)
SetTeams(5)
SetGamePlacement(MAP_PLACEMENT_USE_MAP_SETTINGS)
DefineStartLocation(0, -128.0, -832.0)
DefineStartLocation(1, 3520.0, 256.0)
DefineStartLocation(2, 1472.0, 2496.0)
DefineStartLocation(3, 2240.0, -1600.0)
DefineStartLocation(4, -704.0, 192.0)
InitCustomPlayerSlots()
InitCustomTeams()
InitAllyPriorities()
end

