declare var gg_trg_Melee_Initialization: trigger;
declare var gg_trg_Train_demons: trigger;
declare var gg_unit_ndke_0076: unit;
declare var gg_rct_Human_rescue_base: rect;
declare var gg_rct_Orc_rescue_base: rect;
declare var gg_rct_Human_rescue_trigger: rect;
declare var gg_trg_Rescue_human: trigger;
declare var gg_trg_Rescue_orc: trigger;
declare var gg_rct_Defense: rect;
